# Generated by Django 2.1.15 on 2020-06-24 11:36

from django.db import migrations


def forwards(apps, schema_editor):
    Category = apps.get_model('news', 'Category')
    Category.objects.create(category="Dummy Category", slug="dummy-category")


def backwards(apps, schema_editor):
    Category = apps.get_model('news', 'Category')
    obj = Category.objects.get(slug="dummy-category")
    obj.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200624_1135'),
    ]

    operations = [
        migrations.RunPython(code=forwards, reverse_code=backwards)
    ]
