# Generated by Django 2.1.15 on 2020-06-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_auto_20200624_1539"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="news.Category",
            ),
            preserve_default=False,
        ),
    ]
