# Generated by Django 2.2 on 2020-11-11 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_relatedarticlecardplugin_relatedarticleplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedarticleplugin',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category to add the most recent articles.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Category'),
        ),
        migrations.AddField(
            model_name='relatedarticleplugin',
            name='num_articles',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
