# Generated by Django 3.2.6 on 2021-08-31 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210812_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
