# Generated by Django 3.2.6 on 2021-08-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_update_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='plugin_text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='relatedarticleplugin',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='\n        Limit recent articles based on tags. This is the\n        first priority in what articles are returned and will be overriden\n        if you also select a category.\n        ', to='news.ArticleTag'),
        ),
    ]
