# Generated by Django 3.2.11 on 2022-01-26 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import swapper


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('giant_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedArticlePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='giant_news_relatedarticleplugin', serialize=False, to='cms.cmsplugin')),
                ('num_articles', models.PositiveIntegerField(default=3, help_text='\n        This will decide how many articles to return. By\n        default this plugin will return this number articles\n        based on when they were created. You can filter the\n        articles more using the fields below\n        ')),
                ('category', models.ForeignKey(blank=True, help_text='\n        Limit recent articles based on a category. This will\n        override the tags that you choose and will filter on this category\n        ONLY.\n        ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='giant_news.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='\n        Limit recent articles based on tags. This is the\n        first priority in what articles are returned and will be overriden\n        if you also select a category.\n        ', to='giant_news.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RelatedArticleCardPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='giant_news_relatedarticlecardplugin', serialize=False, to='cms.cmsplugin')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_articles', to=swapper.get_model_name('giant_news', 'Article'), verbose_name='Article')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
