# Generated by Django 3.2.11 on 2022-09-12 04:59

from django.db import migrations, models
import django.db.models.deletion
import giant_news.models.article


class Migration(migrations.Migration):

    dependencies = [
        ('giant_news', '0004_auto_20220601_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=giant_news.models.article._default_author, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='giant_news_articles', to='giant_news.author'),
        ),
    ]
