# Generated by Django 4.2.3 on 2023-07-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giant_news", "0006_alter_article_author_alter_article_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relatedarticleplugin",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="\n        If you want to display a title above the articles,\n        enter it here.\n        ",
                max_length=255,
            ),
        ),
    ]
