# Generated by Django 4.2.24 on 2025-09-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giant_news", "0007_relatedarticleplugin_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="external_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Add additional link to connect author to a social media account e.g. LinkedIn.",
            ),
        ),
    ]
